# testing PUT songs route, no changes are made to the song, we are only reinserting the name to ensure the put route works
put http://localhost:3000/song/661f1a2b3c4d5e6f7a8b9c01
Content-Type: application/json

{
    "name": "Bohemian Rhapsody"
}
###