## testing POST song route
post http://localhost:3000/song
{
    "name": "song-test",
    "len_in_sec": 99999,
    "len_in_min": 2,
    "artist_id": {
        "$oid": "6a249a0cdee876b0b4e64e8b"
    },
    "album_id": {
        "$oid": "1561651651651"
    },
    "playlists_in": [
        {
            "$oid": "1561651651651"
        },
        {
            "$oid": "1561651651651"
        }
    ]
}
###

# testing PUT songs route, no changes are made to the song, we are only reinserting the name to ensure the put route works
put http://localhost:3000/song/661f1a2b3c4d5e6f7a8b9c01
Content-Type: application/json

{
    "name": "Bohemian Rhapsody"
}
###

# testing put and post validation
get http://localhost:3000/song
###


put http://localhost:3000/song/6a279d02756a7fcd0b119727
Content-Type: application/json

{
    "name": ""
}
###

post http://localhost:3000/song/
Content-Type: application/json

{
    "_id":"",
    "name": "",
    "len_in_sec": "",
    "len_in_min": "",
    "artist_id": "",
    "album_id": "",
    "playlist_in": ""
}

###